# Generated by Django 2.1 on 2018-08-29 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20180823_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='img',
            field=models.ImageField(blank=True, height_field=100, upload_to='images/', width_field=100),
        ),
    ]
